import { Link, createFileRoute } from "@tanstack/react-router";
import { Minus, Plus, ShoppingBag, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { formatPrice, useCart } from "@/lib/cart";

export const Route = createFileRoute("/cart")({ component: CartPage });

function CartPage() {
  const { items, subtotal, incrementItem, decrementItem, removeItem } = useCart();
  return <main className="min-h-[70vh] bg-[oklch(0.985_0.01_320)] px-4 py-12 sm:px-6"><div className="mx-auto max-w-5xl"><div className="flex items-center gap-3"><ShoppingBag className="size-7 text-primary" /><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-primary">Shopping bag</p><h1 className="font-display text-4xl font-bold">Your Cart</h1></div></div>{items.length === 0 ? <section className="mt-8 rounded-[2rem] border border-border bg-card p-10 text-center shadow-soft"><h2 className="text-2xl font-bold">Your cart is empty</h2><p className="mt-2 text-muted-foreground">Choose a ready-made design or start a custom request.</p><Button className="mt-6" variant="hero" asChild><Link to="/shop">Shop Products</Link></Button></section> : <div className="mt-8 grid items-start gap-6 lg:grid-cols-[minmax(0,1fr)_320px]"><section className="space-y-3">{items.map((item) => <article key={`${item.productId}-${item.option}-${item.color}`} className="flex gap-4 rounded-[1.5rem] border border-border bg-card p-4 shadow-soft">{item.imageUrl && <img src={item.imageUrl} alt="" className="size-28 rounded-xl object-cover" />}<div className="min-w-0 flex-1"><p className="font-bold">{item.name}</p><p className="mt-1 text-xs text-muted-foreground">{[item.color, item.option].filter(Boolean).join(" • ")}</p><p className="mt-3 font-bold text-primary">{formatPrice(item.price)}</p><div className="mt-4 flex flex-wrap items-center gap-2"><div className="flex items-center rounded-full border border-border"><Button size="icon-sm" variant="ghost" onClick={() => decrementItem(item.productId)}><Minus /></Button><span className="min-w-8 text-center text-sm font-bold">{item.quantity}</span><Button size="icon-sm" variant="ghost" onClick={() => incrementItem(item.productId)}><Plus /></Button></div><Button size="sm" variant="ghost" onClick={() => removeItem(item.productId)}><Trash2 /> Remove</Button></div></div><strong>{formatPrice(item.price * item.quantity)}</strong></article>)}</section><aside className="rounded-[1.75rem] border border-border bg-card p-5 shadow-soft"><h2 className="text-xl font-bold">Order Summary</h2><div className="mt-5 flex justify-between border-b border-border pb-4"><span className="text-muted-foreground">Subtotal</span><strong>{formatPrice(subtotal)}</strong></div><p className="mt-4 text-xs leading-relaxed text-muted-foreground">Shipping is calculated at checkout from the delivery address and package size/weight.</p><Button variant="hero" className="mt-5 w-full" asChild><Link to="/checkout">Checkout</Link></Button><Button variant="soft" className="mt-3 w-full" asChild><Link to="/shop">Continue Shopping</Link></Button></aside></div>}</div></main>;
}
