-- JMB 2 Creations operational customer accounts + custom request chat
-- Run AFTER jmb-catalog-phase2.sql.

create extension if not exists pgcrypto;

create table if not exists public.jmb_custom_requests (
  id uuid primary key default gen_random_uuid(),
  request_number bigint generated by default as identity unique,
  customer_user_id uuid not null references auth.users(id) on delete cascade,
  customer_name text not null,
  customer_email text not null,
  product_family text not null,
  idea text not null,
  colors text,
  size text,
  quantity integer not null default 1 check (quantity > 0),
  fulfillment text not null default 'Not sure' check (fulfillment in ('Shipping','Local Pickup','Not sure')),
  status text not null default 'New' check (status in ('New','In Review','Quoted','Accepted','Declined','Converted')),
  quote numeric(10,2) check (quote is null or quote >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.jmb_custom_messages (
  id uuid primary key default gen_random_uuid(),
  request_id uuid not null references public.jmb_custom_requests(id) on delete cascade,
  sender text not null check (sender in ('customer','admin')),
  sender_user_id uuid references auth.users(id) on delete set null,
  body text not null check (length(trim(body)) > 0),
  created_at timestamptz not null default now()
);

create index if not exists jmb_custom_requests_customer_idx on public.jmb_custom_requests(customer_user_id, created_at desc);
create index if not exists jmb_custom_messages_request_idx on public.jmb_custom_messages(request_id, created_at);

drop trigger if exists jmb_custom_requests_touch on public.jmb_custom_requests;
create trigger jmb_custom_requests_touch before update on public.jmb_custom_requests
for each row execute function public.jmb_touch_updated_at();

alter table public.jmb_custom_requests enable row level security;
alter table public.jmb_custom_messages enable row level security;

-- Customers can create/read their own requests.
drop policy if exists "customers insert own JMB requests" on public.jmb_custom_requests;
create policy "customers insert own JMB requests"
on public.jmb_custom_requests for insert to authenticated
with check (customer_user_id = auth.uid());

drop policy if exists "customers read own JMB requests" on public.jmb_custom_requests;
create policy "customers read own JMB requests"
on public.jmb_custom_requests for select to authenticated
using (
  customer_user_id = auth.uid()
  or exists (select 1 from public.jmb_admins a where a.user_id = auth.uid())
);

-- Only JMB admins can change quote/status.
drop policy if exists "JMB admins update custom requests" on public.jmb_custom_requests;
create policy "JMB admins update custom requests"
on public.jmb_custom_requests for update to authenticated
using (exists (select 1 from public.jmb_admins a where a.user_id = auth.uid()))
with check (exists (select 1 from public.jmb_admins a where a.user_id = auth.uid()));

-- Customer/admin can read messages for requests they are allowed to see.
drop policy if exists "participants read JMB custom messages" on public.jmb_custom_messages;
create policy "participants read JMB custom messages"
on public.jmb_custom_messages for select to authenticated
using (
  exists (
    select 1 from public.jmb_custom_requests r
    where r.id = request_id
      and (
        r.customer_user_id = auth.uid()
        or exists (select 1 from public.jmb_admins a where a.user_id = auth.uid())
      )
  )
);

-- Customers can send messages only into their own request and must identify themselves as customer.
drop policy if exists "customers send JMB custom messages" on public.jmb_custom_messages;
create policy "customers send JMB custom messages"
on public.jmb_custom_messages for insert to authenticated
with check (
  sender = 'customer'
  and sender_user_id = auth.uid()
  and exists (
    select 1 from public.jmb_custom_requests r
    where r.id = request_id and r.customer_user_id = auth.uid()
  )
);

-- JMB admins can send messages to any request.
drop policy if exists "JMB admins send custom messages" on public.jmb_custom_messages;
create policy "JMB admins send custom messages"
on public.jmb_custom_messages for insert to authenticated
with check (
  sender = 'admin'
  and sender_user_id = auth.uid()
  and exists (select 1 from public.jmb_admins a where a.user_id = auth.uid())
);
