import { Link, createFileRoute } from "@tanstack/react-router";
import { ArrowLeft, PackageCheck, Truck } from "lucide-react";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { getValidCustomerSession } from "@/lib/customer-auth";
import { fetchCustomerOrderItems, fetchCustomerOrders, orderCode, type JmbOrder, type JmbOrderItem } from "@/lib/orders";

export const Route = createFileRoute("/orders/$orderId")({ component: CustomerOrderPage });

function CustomerOrderPage() {
  const { orderId } = Route.useParams(); const [order, setOrder] = useState<JmbOrder | null>(null); const [items, setItems] = useState<JmbOrderItem[]>([]); const [loading, setLoading] = useState(true); const [signedIn, setSignedIn] = useState(true);
  useEffect(() => { (async () => { const session = await getValidCustomerSession(); if (!session) { setSignedIn(false); setLoading(false); return; } try { const [orders, lines] = await Promise.all([fetchCustomerOrders(), fetchCustomerOrderItems(orderId)]); setOrder(orders.find((row) => row.id === orderId) ?? null); setItems(lines); } finally { setLoading(false); } })(); }, [orderId]);
  const money = (v: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(Number(v) || 0);
  if (loading) return <main className="grid min-h-[70vh] place-items-center"><p className="text-sm text-muted-foreground">Loading order...</p></main>;
  if (!signedIn) return <main className="mx-auto max-w-xl px-4 py-20 text-center"><h1 className="font-display text-3xl font-bold">Sign in to view this order.</h1><Button variant="hero" className="mt-6" asChild><Link to="/account">Customer Sign In</Link></Button></main>;
  if (!order) return <main className="mx-auto max-w-xl px-4 py-20 text-center"><h1 className="font-display text-3xl font-bold">Order not found.</h1><Button variant="soft" className="mt-6" asChild><Link to="/account">Back to Account</Link></Button></main>;
  return <main className="min-h-[75vh] bg-[oklch(0.985_0.01_320)] px-4 py-10 sm:px-6"><div className="mx-auto max-w-4xl"><Button variant="soft" size="sm" asChild><Link to="/account"><ArrowLeft /> Account</Link></Button><section className="mt-6 rounded-[2rem] border border-border bg-card p-6 shadow-soft sm:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-primary">Order details</p><h1 className="mt-2 font-display text-4xl font-bold">{orderCode(order)}</h1><p className="mt-2 text-sm text-muted-foreground">Placed {new Date(order.created_at).toLocaleDateString()}</p></div><span className="rounded-full bg-secondary px-4 py-2 text-sm font-bold text-primary">{order.status}</span></div><div className="mt-7 space-y-3">{items.map((item) => <div key={item.id} className="flex items-center gap-4 rounded-2xl border border-border p-4">{item.image_url && <img src={item.image_url} alt="" className="size-20 rounded-xl object-cover" />}<div className="min-w-0 flex-1"><p className="font-bold">{item.quantity}× {item.name}</p><p className="mt-1 text-xs text-muted-foreground">{[item.team,item.option].filter(Boolean).join(" • ")}</p></div><strong>{money(item.line_total)}</strong></div>)}</div><div className="ml-auto mt-6 max-w-sm space-y-2 text-sm"><div className="flex justify-between"><span className="text-muted-foreground">Subtotal</span><strong>{money(order.subtotal)}</strong></div><div className="flex justify-between"><span className="text-muted-foreground">Shipping</span><strong>{money(order.shipping_amount)}</strong></div><div className="flex justify-between border-t border-border pt-3 text-lg"><span>Total</span><strong>{money(order.total)}</strong></div></div><div className="mt-8 grid gap-4 sm:grid-cols-2"><div className="rounded-2xl bg-secondary/30 p-5"><PackageCheck className="size-5 text-primary" /><p className="mt-2 text-sm text-muted-foreground">Fulfillment</p><p className="font-bold">{order.fulfillment}</p></div><div className="rounded-2xl bg-secondary/30 p-5"><Truck className="size-5 text-primary" /><p className="mt-2 text-sm text-muted-foreground">Tracking</p><p className="font-bold">{order.tracking_code || "Not available yet"}</p>{order.tracking_carrier && <p className="text-xs text-muted-foreground">{order.tracking_carrier}</p>}</div></div></section></div></main>;
}
